version: 2.1
orbs:

  node: circleci/node@3.0.1
  aws-s3: circleci/aws-s3@1.0.16

jobs:

  build:
    parameters:
      env:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm ci
      - run: npm run build:<< parameters.env >>
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
        cache-path: ./node_modules
      - run: npm run test:unit

  deploy:
    parameters:
      env:
        type: string
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ./workspace
      - aws-s3/sync:
          arguments: '--delete'
          from: ./workspace/dist
          to: 's3://icyfry-website/<< parameters.env >>'

workflows:

  build-and-deploy-staging:
    jobs:
      - build:
          filters:
            branches:
              only: develop
          env: staging
      - test:
          requires:
            - build
      - deploy:
          env: staging
          requires:
            - test

  build-and-deploy-prod:
    jobs:
      - build:
          filters:
            branches:
              only: master
          env: prod
      - test:
          requires:
            - build
      - deploy:
          env: prod
          requires:
            - test